export const Api_endPoints = {
  admin_login: "admin/management/login",
  getAdminById: "/admin/management/admin/",
  all: "/film/management/all_raw",
  genre: "/film/management/genre/users/",
  byYear: "/film/management/query-year/",
  byTitle: "/film/management/query-title/",
  byId: "/film/management/query-id/",
  allG: "/film/management/all?page=1&limit=20",
  find: "/film/management/genre/query/",
  allSeries: "/series/management/all?page=1&limit=20",
  seriesRel: "/series/management/rel/",
  seriesSeasonsRel: "/series/management/seasons-rel/",
  postEpisode: "/series/management/setEpisodes",
  updateSeries: "/series/management/update/series/",
  updateEpisode: "/series/management/update/episodes/:id&:season&:episode",
  generateSeasonEpisodes: "series/management/generate/seasons-episodes/",
  deleteAllSeasonEpisodes: "series/management/delete/season_episodes/",
  deleteSeason: "series/management/delete/season/",
  deleteEpisode: "series/management/delete/episodes/",
};
