import Head from "next/head";
import Image from "next/image";
import { MainBody } from "../components/Mainbody";
import { AxiosInstance } from "../utils/BaseUrl";

async function getServerSideProps() {
  const data = await AxiosInstance.get("api/admin/alert-mode").then(
    (e) => e.data.mode
  );

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainBody>
        <h1>Hey</h1>
      </MainBody>
    </div>
  );
}
