import Head from "next/head";
import Image from "next/image";
import { MainBody } from "../components/Mainbody";
import { AxiosInstance } from "../utils/BaseUrl";
import { parseCookies } from "nookies";
import Center from "../components/Center";

export async function getServerSideProps(ctx) {
  const { ["royalDashboard-Admin-Token"]: Token } = parseCookies(ctx);

  if (!Token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const data = await AxiosInstance.get("api/admin/alert-mode").then(
    (e) => e.data.mode
  );

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  console.log(data);
  return (
    <div className="flex">
      <Head>
        <title>Royal Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainBody>
        {/* <Center movies={5} users={0} usersList={0} alertMode={data} /> */}
      </MainBody>
    </div>
  );
}
